# Generated by Django 3.1.5 on 2021-04-04 22:18

import config.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_to_import', models.FileField(help_text='The .csv file containing records of teachers.', upload_to='record_csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv']), django_clamd.validators.validate_file_infection], verbose_name='Records to Import')),
                ('images_to_import', models.FileField(help_text='The .zip file containing images for teacher profiles.', upload_to='image_zip/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), django_clamd.validators.validate_file_infection], verbose_name='Images to Import')),
                ('total_records', models.PositiveIntegerField(default=0, validators=[django.core.validators.validate_integer], verbose_name='Total Records')),
                ('status', models.CharField(choices=[('P', 'Processing'), ('S', 'Success'), ('E', 'Error')], default='P', max_length=1, verbose_name='Task Status')),
                ('log', models.TextField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Teacher's first name.", max_length=26, validators=[config.validators.validate_name], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="Teacher's last name.", max_length=26, validators=[config.validators.validate_name], verbose_name='Last Name')),
                ('picture', models.ImageField(blank=True, help_text="Teacher's picture (must match with picture in photo ID below) in .png or .jpg format. (Max 2 MB)", upload_to='picture/', validators=[django_clamd.validators.validate_file_infection], verbose_name='Profile Picture')),
                ('email', models.EmailField(help_text="Teacher's e-mail address.", max_length=320, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text="Teacher's valid mobile number.", max_length=16, unique=True, validators=[config.validators.validate_phone_number], verbose_name='Phone Number')),
                ('room_number', models.CharField(help_text='Your valid mobile number for OTP verification.', max_length=14, validators=[config.validators.validate_room_number], verbose_name='Room Number')),
                ('subject_taught', models.TextField(blank=True, help_text='All the subjects taught by teacher.', max_length=1000, validators=[config.validators.validate_name], verbose_name='Subjects Taught')),
            ],
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name'], name='directory_t_last_na_a43f27_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['subject_taught'], name='directory_t_subject_f13d59_idx'),
        ),
        migrations.AddField(
            model_name='importtask',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
